import { Hasher } from "./hasher";
import { Scheduler } from "./scheduler";
import { MessageQueue } from "./message-queue";
import { ApClientRepository } from "./ap-client-repository";
import { DeviceRepository } from "./device-repository";
import { IdentityProvider } from "./identity-provider";
import { NodeEventRepository } from "./node-event-repository";
import { VendorRepository } from "./vendor-repository";
import { UserRepository } from "./user-repository";
import { OrganizationRepository } from "./organization-repository";
import { TagRepository } from "./tag-repository";
import { SiteRepository } from "./site-repository";
import { TermsOfUseRepository } from "./terms-of-use-repository";
import { AlertRepository } from "./alert-repository";
import { NodeRepository } from "./node-repository";
import { LicenseRepository } from "./license-repository";
import { LocalMapImageFs } from "./local-map-image-fs";
import { LocalMapRepository } from "./local-map-repository";
import { Lock } from "./lock";
import { ImageTransformer } from "./image-transformer";
import { ActionLogRepository } from "./action-log-repository";
import { NotificationConfigRepository } from "./notification-config-repository";
import { NodeConfigRepository } from "./node-config-repository";
import { NodeController } from "./node-controller";
import { FirmwareRepository } from "./firmware-repository";
import { FirmwareImageFs } from "./firmware-image-fs";
import { RawMessageFs } from "./raw-message-fs";
import { Runner } from "./runner";
import { JobRepository } from "./job-repository";
import { Logger } from "./logger";
import { AnnouncementRepository } from "./announcement-repository";
import { SecretManager } from "./secret-manager";
import { VendorProvider } from "./vendor-provider";
import { EmailDistributor } from "./email-distributor";
import { Dispatcher } from "./dispatcher";
import { MetricRepository } from "./metric-repository";

export type Infrastructure = {
  identityProvider: IdentityProvider;
  userRepository: UserRepository;
  organizationRepository: OrganizationRepository;
  tagRepository: TagRepository;
  siteRepository: SiteRepository;
  termsOfUseRepository: TermsOfUseRepository;
  nodeRepository: NodeRepository;
  licenseRepository: LicenseRepository;
  localMapImageFs: LocalMapImageFs;
  localMapRepository: LocalMapRepository;
  logger: Logger;
  lock: Lock;
  runner: Runner;
  rawMessageFs: RawMessageFs;
  imageTransformer: ImageTransformer;
  actionLogRepository: ActionLogRepository;
  vendorRepository: VendorRepository;
  vendorProvider: VendorProvider;
  notificationConfigRepository: NotificationConfigRepository;
  nodeConfigRepository: NodeConfigRepository;
  nodeController: NodeController;
  firmwareRepository: FirmwareRepository;
  firmwareImageFs: FirmwareImageFs;
  jobRepository: JobRepository;
  apClientRepository: ApClientRepository;
  hasher: Hasher;
  announcementRepository: AnnouncementRepository;
  secretManager: SecretManager;
  deviceRepository: DeviceRepository;
  messageQueue: MessageQueue;
  emailDistributor: EmailDistributor;
  dispatcher: Dispatcher;
  metricRepository: MetricRepository;
  nodeEventRepository: NodeEventRepository;
  alertRepository: AlertRepository;
  scheduler: Scheduler;
};
